package com.evertvd.greendaoinventario.modelo.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.evertvd.greendaoinventario.modelo.Conteo;

import com.evertvd.greendaoinventario.modelo.Historial;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HISTORIAL".
*/
public class HistorialDao extends AbstractDao<Historial, Long> {

    public static final String TABLENAME = "HISTORIAL";

    /**
     * Properties of entity Historial.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Cantidad = new Property(1, Integer.class, "cantidad", false, "CANTIDAD");
        public final static Property Observacion = new Property(2, String.class, "observacion", false, "OBSERVACION");
        public final static Property Fecharegistro = new Property(3, String.class, "fecharegistro", false, "FECHAREGISTRO");
        public final static Property Fechamodificacion = new Property(4, String.class, "fechamodificacion", false, "FECHAMODIFICACION");
        public final static Property Tipo = new Property(5, Integer.class, "tipo", false, "TIPO");
        public final static Property Conteo_id = new Property(6, Long.class, "conteo_id", false, "CONTEO_ID");
    }

    private DaoSession daoSession;

    private Query<Historial> conteo_HistorialListQuery;

    public HistorialDao(DaoConfig config) {
        super(config);
    }
    
    public HistorialDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HISTORIAL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CANTIDAD\" INTEGER," + // 1: cantidad
                "\"OBSERVACION\" TEXT," + // 2: observacion
                "\"FECHAREGISTRO\" TEXT," + // 3: fecharegistro
                "\"FECHAMODIFICACION\" TEXT," + // 4: fechamodificacion
                "\"TIPO\" INTEGER," + // 5: tipo
                "\"CONTEO_ID\" INTEGER);"); // 6: conteo_id
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_HISTORIAL_CONTEO_ID ON HISTORIAL" +
                " (\"CONTEO_ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HISTORIAL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Historial entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer cantidad = entity.getCantidad();
        if (cantidad != null) {
            stmt.bindLong(2, cantidad);
        }
 
        String observacion = entity.getObservacion();
        if (observacion != null) {
            stmt.bindString(3, observacion);
        }
 
        String fecharegistro = entity.getFecharegistro();
        if (fecharegistro != null) {
            stmt.bindString(4, fecharegistro);
        }
 
        String fechamodificacion = entity.getFechamodificacion();
        if (fechamodificacion != null) {
            stmt.bindString(5, fechamodificacion);
        }
 
        Integer tipo = entity.getTipo();
        if (tipo != null) {
            stmt.bindLong(6, tipo);
        }
 
        Long conteo_id = entity.getConteo_id();
        if (conteo_id != null) {
            stmt.bindLong(7, conteo_id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Historial entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer cantidad = entity.getCantidad();
        if (cantidad != null) {
            stmt.bindLong(2, cantidad);
        }
 
        String observacion = entity.getObservacion();
        if (observacion != null) {
            stmt.bindString(3, observacion);
        }
 
        String fecharegistro = entity.getFecharegistro();
        if (fecharegistro != null) {
            stmt.bindString(4, fecharegistro);
        }
 
        String fechamodificacion = entity.getFechamodificacion();
        if (fechamodificacion != null) {
            stmt.bindString(5, fechamodificacion);
        }
 
        Integer tipo = entity.getTipo();
        if (tipo != null) {
            stmt.bindLong(6, tipo);
        }
 
        Long conteo_id = entity.getConteo_id();
        if (conteo_id != null) {
            stmt.bindLong(7, conteo_id);
        }
    }

    @Override
    protected final void attachEntity(Historial entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Historial readEntity(Cursor cursor, int offset) {
        Historial entity = new Historial( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // cantidad
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // observacion
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // fecharegistro
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // fechamodificacion
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // tipo
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6) // conteo_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Historial entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCantidad(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setObservacion(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFecharegistro(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setFechamodificacion(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTipo(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setConteo_id(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Historial entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Historial entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Historial entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "historialList" to-many relationship of Conteo. */
    public List<Historial> _queryConteo_HistorialList(Long conteo_id) {
        synchronized (this) {
            if (conteo_HistorialListQuery == null) {
                QueryBuilder<Historial> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Conteo_id.eq(null));
                conteo_HistorialListQuery = queryBuilder.build();
            }
        }
        Query<Historial> query = conteo_HistorialListQuery.forCurrentThread();
        query.setParameter(0, conteo_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getConteoDao().getAllColumns());
            builder.append(" FROM HISTORIAL T");
            builder.append(" LEFT JOIN CONTEO T0 ON T.\"CONTEO_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Historial loadCurrentDeep(Cursor cursor, boolean lock) {
        Historial entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Conteo conteo = loadCurrentOther(daoSession.getConteoDao(), cursor, offset);
        entity.setConteo(conteo);

        return entity;    
    }

    public Historial loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Historial> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Historial> list = new ArrayList<Historial>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Historial> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Historial> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
